/* REST API's */
const INVOICE_ROOT_URL = "/api/invoices/";
const PRODUCTS_ROOT_URL = "/api/products/";
const CUSTOMERS_ROOT_URL = "/api/customers/";

export const GET_ALL_INVOICES = 'GET_ALL_INVOICES';
export const GET_ALL_INVOICES_SUCCESS = 'GET_ALL_INVOICES_SUCCESS';
export const GET_ALL_INVOICES_REJECTED = 'GET_ALL_INVOICES_REJECTED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_REJECTED = 'GET_PRODUCTS_REJECTED';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';